Update adafruit_tlv493d.py
adafruit/Adafruit_CircuitPython_TLV493D pull request #16
Opened 2022-09-04 23:14 UTC by BrianPugh

Fixed units in docstring. Alternatively, multiply the returned values by 1000 in `_unpack_and_scale` to report microteslas (what all the other magnetic sensors from adafruit report).

2022-09-06 16:09 UTC, BrianPugh commented
I suppose according to the design guide, changing to microteslas would be better:

https://docs.circuitpython.org/en/7.3.x/docs/design_guide.html#sensor-properties-and-units

2022-09-08 14:00 UTC, tekktrik commented
I'll take a look at this in a couple hours :)

2022-09-08 16:53 UTC, tekktrik requested changes
Yeah, you're right, per the CircuitPython design guide, let's return this in microtesla.  So instead you can change just return `binval * 98.0` in `_unpack_and_scale()` and we can give this a major revision update!

2022-09-08 17:00 UTC, tekktrik approved these changes
Thanks for this, looks good to me!

2022-09-08 17:01 UTC, merged

2022-09-08 17:11 UTC, BrianPugh commented
thanks @tekktrik ! Also a little self promotion that you or people at adafruit might find interesting (using this and the other adafruit magnetic sensor drivers):

https://github.com/BrianPugh/magnetometer